/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progiciel_cryptool;

import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author DELL
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Acceuil() {
        initComponents();
    }

    public JLabel getLblWelcome() {
        return lblWelcome;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnAsymetrique() {
        return btnAsymetrique;
    }

    public JButton getBtnDH() {
        return btnDH;
    }

    public JButton getBtnPairKey() {
        return btnPairKey;
    }

    public JButton getBtnSecKey() {
        return btnSecKey;
    }

    public JButton getBtnSign() {
        return btnSign;
    }

    public JButton getBtnSymetrique() {
        return btnSymetrique;
    }

    public JButton getBtnHybride() {
        return btnHybride;
    }

    public JButton getBtnECC() {
        return btnECC;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        btnPairKey = new javax.swing.JButton();
        btnSecKey = new javax.swing.JButton();
        btnAsymetrique = new javax.swing.JButton();
        btnHybride = new javax.swing.JButton();
        btnSign = new javax.swing.JButton();
        btnSymetrique = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDH = new javax.swing.JButton();
        btnECC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(102, 102, 102));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CryptooX");

        btnLogout.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogout)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 45));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("to");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 22, 21));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CryptooX");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 136, 32));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progiciel_cryptool/Logo1.png"))); // NOI18N
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 31));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progiciel_cryptool/images-rem.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, -1));

        jPanel8.setBackground(new java.awt.Color(60, 127, 204));

        lblClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setPreferredSize(new java.awt.Dimension(17, 17));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.setPreferredSize(new java.awt.Dimension(17, 17));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnPairKey.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnPairKey.setForeground(new java.awt.Color(153, 153, 255));
        btnPairKey.setText("NewPaireKey");
        btnPairKey.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPairKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPairKeyActionPerformed(evt);
            }
        });

        btnSecKey.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSecKey.setForeground(new java.awt.Color(153, 153, 255));
        btnSecKey.setText("NewSecretKey");
        btnSecKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecKeyActionPerformed(evt);
            }
        });

        btnAsymetrique.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAsymetrique.setForeground(new java.awt.Color(153, 153, 255));
        btnAsymetrique.setText("Asymétrique");
        btnAsymetrique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsymetriqueActionPerformed(evt);
            }
        });

        btnHybride.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnHybride.setForeground(new java.awt.Color(153, 153, 255));
        btnHybride.setText("Hybride");

        btnSign.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSign.setForeground(new java.awt.Color(153, 153, 255));
        btnSign.setText("Signature");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });

        btnSymetrique.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSymetrique.setForeground(new java.awt.Color(153, 153, 255));
        btnSymetrique.setText("Symétrique");
        btnSymetrique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymetriqueActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progiciel_cryptool/background (8).jpg"))); // NOI18N
        jLabel7.setOpaque(true);
        jLabel7.setSize(601,401);

        btnDH.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnDH.setForeground(new java.awt.Color(153, 153, 255));
        btnDH.setText("DH");
        btnDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDHActionPerformed(evt);
            }
        });

        btnECC.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnECC.setForeground(new java.awt.Color(153, 153, 255));
        btnECC.setText("ECC");
        btnECC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSymetrique, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPairKey, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSecKey, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnAsymetrique)
                        .addGap(12, 12, 12)
                        .addComponent(btnHybride, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSign, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDH, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnECC, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSymetrique)
                    .addComponent(btnPairKey)
                    .addComponent(btnSecKey)
                    .addComponent(btnAsymetrique)
                    .addComponent(btnHybride)
                    .addComponent(btnSign)
                    .addComponent(btnDH)
                    .addComponent(btnECC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSecKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecKeyActionPerformed
        GenSecKey seckey = new GenSecKey();
        seckey.setVisible(true);
        seckey.setLocationRelativeTo(null);
        //this.dispose();
    }//GEN-LAST:event_btnSecKeyActionPerformed

    private void btnAsymetriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsymetriqueActionPerformed
        String option[] = {"Chiffrer", "Déchiffrer"};
        int opt = JOptionPane.showOptionDialog(null, "Choisissez une option", "Saved!", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, option, option[0]);
        if (opt == 0) {
            AsymetriqueCipher asym = new AsymetriqueCipher();
            asym.setVisible(true);
            asym.setLocationRelativeTo(null);
            //this.dispose();
        } else if (opt == 1) {
            AsymetriqueDecipher asym = new AsymetriqueDecipher();
            asym.setVisible(true);
            asym.setLocationRelativeTo(null);
            //this.dispose();
        }
    }//GEN-LAST:event_btnAsymetriqueActionPerformed

    private void btnPairKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPairKeyActionPerformed
        GenPairKey genkey = new GenPairKey();
        genkey.setVisible(true);
        genkey.setLocationRelativeTo(null);
        //this.dispose();
    }//GEN-LAST:event_btnPairKeyActionPerformed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setForeground(Color.white);
        Border borderLabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        lblMinimize.setBorder(borderLabel);
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setForeground(Color.black);
        Border borderLabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        lblMinimize.setBorder(borderLabel);
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setForeground(Color.red);
        Border borderLabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        lblClose.setBorder(borderLabel);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setForeground(Color.black);
        Border borderLabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        lblClose.setBorder(borderLabel);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnSymetriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymetriqueActionPerformed

        String option[] = {"Chiffrer", "Déchiffrer"};
        int opt = JOptionPane.showOptionDialog(null, "Choisissez une option", "Saved!", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, option, option[0]);
        if (opt == 0) {
            SymetriqueCipher sym = new SymetriqueCipher();
            sym.setVisible(true);
            sym.setLocationRelativeTo(null);
            //this.dispose();
        } else if (opt == 1) {
            SymetriqueDecipher sym = new SymetriqueDecipher();
            sym.setVisible(true);
            sym.setLocationRelativeTo(null);
            //this.dispose();
        }
    }//GEN-LAST:event_btnSymetriqueActionPerformed

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        String option[] = {"Signer", "Vérifier"};
        int opt = JOptionPane.showOptionDialog(null, "Choisissez une option", "Saved!", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, option, option[0]);
        if (opt == 0) {
            Signature sign = new Signature();
            sign.setVisible(true);
            sign.setLocationRelativeTo(null);
            //this.dispose();
        } else if (opt == 1) {
            VerifSignature verif = new VerifSignature();
            verif.setVisible(true);
            verif.setLocationRelativeTo(null);
            //this.dispose();
        }
    }//GEN-LAST:event_btnSignActionPerformed

    private void btnDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDHActionPerformed
        Dh dh = new Dh();
        dh.setVisible(true);
        dh.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDHActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(btnLogout, "Voulez-vous vraiment quitter? ");
        if (a == JOptionPane.YES_OPTION) {
            dispose();
            Acceuil ac = new Acceuil();
            ac.setVisible(true);
            ac.getBtnLogout().setVisible(false);
            ac.getBtnAsymetrique().setVisible(false);
            ac.getBtnDH().setVisible(false);
            ac.getBtnPairKey().setVisible(false);
            ac.getBtnSecKey().setVisible(false);
            ac.getBtnSign().setVisible(false);
            ac.getBtnSymetrique().setVisible(false);
            ac.getBtnHybride().setVisible(false);
            ac.getBtnECC().setVisible(false);
            Dimension tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            int hauteur = (int) tailleEcran.getHeight();
            int largeur = (int) tailleEcran.getWidth();
            ac.setSize(largeur, hauteur);
            try {
                Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "login failled");
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnECCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECCActionPerformed
        Ecc ec = new Ecc();
        ec.setVisible(true);
        ec.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnECCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Acceuil ac = new Acceuil();
                ac.setVisible(true);
                ac.getBtnLogout().setVisible(false);
                ac.getBtnAsymetrique().setVisible(false);
                ac.getBtnDH().setVisible(false);
                ac.getBtnPairKey().setVisible(false);
                ac.getBtnSecKey().setVisible(false);
                ac.getBtnSign().setVisible(false);
                ac.getBtnSymetrique().setVisible(false);
                ac.getBtnHybride().setVisible(false);
                ac.getBtnECC().setVisible(false);
                Dimension tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                int hauteur = (int) tailleEcran.getHeight();
                int largeur = (int) tailleEcran.getWidth();
                ac.setSize(largeur, hauteur);
                try {
                    Login log = new Login();
                    log.setVisible(true);
                    log.setLocationRelativeTo(null);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "login failled");
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsymetrique;
    private javax.swing.JButton btnDH;
    private javax.swing.JButton btnECC;
    private javax.swing.JButton btnHybride;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPairKey;
    private javax.swing.JButton btnSecKey;
    private javax.swing.JButton btnSign;
    private javax.swing.JButton btnSymetrique;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
