/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progiciel_cryptool;

import chap2.TestECDSA;
import chap2.Utils;
import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import javax.crypto.SecretKey;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileNameExtensionFilter;
import tp.FonctionsAES;
import tp.FonctionsRSA;

/**
 *
 * @author DELL
 */
public class Hybride extends javax.swing.JFrame {

    private String txtFichier;
    private String txtCle;
    private String choix;
    private String txtDestination;

    public Hybride(String txtFichier, String txtCle, String choix, String txtDestination) {
        this.txtFichier = txtFichier;
        this.txtCle = txtCle;
        this.choix = choix;
        this.txtDestination = txtDestination;
    }

    public JToggleButton getBtnCipher() {
        return btnCipher;
    }

    public void setBtnCipher(JToggleButton btnCipher) {
        this.btnCipher = btnCipher;
    }

    public JButton getBtnFile() {
        return btnFile;
    }

    public void setBtnFile(JButton btnFile) {
        this.btnFile = btnFile;
    }

    public JButton getBtnKey() {
        return btnKey;
    }

    public void setBtnKey(JButton btnKey) {
        this.btnKey = btnKey;
    }

    public Hybride() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFile = new javax.swing.JButton();
        btnKey = new javax.swing.JButton();
        quitter = new javax.swing.JToggleButton();
        btnDecipher = new javax.swing.JToggleButton();
        btnCipher = new javax.swing.JToggleButton();
        txtKey = new javax.swing.JTextField();
        txtFile = new javax.swing.JTextField();
        btnChiffree = new javax.swing.JButton();
        varChoix = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAcceuil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFile.setText("Clé sécréte");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });
        jPanel2.add(btnFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, -1));

        btnKey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKey.setText("CléPublic");
        btnKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActionPerformed(evt);
            }
        });
        jPanel2.add(btnKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 100, -1));

        quitter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        jPanel2.add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        btnDecipher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDecipher.setText("Déchiffrer");
        btnDecipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecipherActionPerformed(evt);
            }
        });
        jPanel2.add(btnDecipher, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        btnCipher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCipher.setText("Chiffrer");
        btnCipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCipherActionPerformed(evt);
            }
        });
        jPanel2.add(btnCipher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyActionPerformed(evt);
            }
        });
        jPanel2.add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, 280, 24));

        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });
        jPanel2.add(txtFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 198, 280, 25));

        btnChiffree.setBackground(new java.awt.Color(102, 204, 255));
        btnChiffree.setText("Choisir un endroit pour l'enregistrement");
        btnChiffree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiffreeActionPerformed(evt);
            }
        });
        jPanel2.add(btnChiffree, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 154, -1, -1));

        varChoix.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varChoix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cipherKey", "cipherMessage", "decipherKey", "decipherMessage" }));
        varChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varChoixActionPerformed(evt);
            }
        });
        jPanel2.add(varChoix, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHOIX");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 430, 380));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progiciel_cryptool/images-rem.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        btnAcceuil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAcceuil.setText("Acceuil");
        btnAcceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceuilActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceuil, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HYBRIDE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 390, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("m2tdsi", "txt");
        chooser.addChoosableFileFilter(filter);
        chooser.setDialogTitle("Choisissez votre fichier");
        int fileState = chooser.showDialog(null, "OK");
        if (fileState == JFileChooser.APPROVE_OPTION);
        File selectedFichier = chooser.getSelectedFile();
        String path = selectedFichier.getAbsolutePath();
        txtFile.setText(path);
        txtFichier = selectedFichier.getAbsolutePath();
        //txtDestination = selectedFichier.getParent();

    }//GEN-LAST:event_btnFileActionPerformed

    private void btnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("m2tdsi", "txt");
        chooser.addChoosableFileFilter(filter);
        chooser.setDialogTitle("Choisissez votre fichier");
        int fileState = chooser.showDialog(null, "OK");
        if (fileState == JFileChooser.APPROVE_OPTION);
        File selectedFichier = chooser.getSelectedFile();
        String path = selectedFichier.getAbsolutePath();
        txtKey.setText(path);
        txtCle = selectedFichier.getAbsolutePath();
    }//GEN-LAST:event_btnKeyActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        dispose();
    }//GEN-LAST:event_quitterActionPerformed

    private void btnDecipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecipherActionPerformed

        try {
            FonctionsRSA fRSA = new FonctionsRSA();
            PrivateKey priv = fRSA.getPriv(txtCle, "RSA");
            fRSA.dechiffrer(priv, txtFichier, txtDestination, "RSA");
            JOptionPane.showMessageDialog(null, "Le chemin du chiffré :" + txtDestination);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur de déchiffrement:");
        }
    }//GEN-LAST:event_btnDecipherActionPerformed

    private void btnCipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCipherActionPerformed

        try {

            FonctionsRSA fRSA = new FonctionsRSA();
            PublicKey secret = fRSA.getPub(txtCle, "RSA");

            fRSA.chiffrer(secret, txtFichier, txtDestination, "RSA");
            JOptionPane.showMessageDialog(null, "Le haché du chiffré :" + txtDestination.getBytes().hashCode());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur de chiffrement:");
        }
    }//GEN-LAST:event_btnCipherActionPerformed

    private void txtKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyActionPerformed

    }//GEN-LAST:event_txtKeyActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileActionPerformed

    private void btnChiffreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiffreeActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("m2tdsi", "txt");
        chooser.addChoosableFileFilter(filter);
        chooser.setDialogTitle("Choisissez l'endroit à enregistrer votre fichier: ");
        int fileState = chooser.showDialog(null, "OK");
        if (fileState == JFileChooser.APPROVE_OPTION);
        File selectedFichier = chooser.getSelectedFile();
        String path = selectedFichier.getAbsolutePath();
        btnChiffree.setText(path + ".txt");
        txtDestination = selectedFichier.getAbsolutePath();
    }//GEN-LAST:event_btnChiffreeActionPerformed

    private void btnAcceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceuilActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnAcceuilActionPerformed

    private void varChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varChoixActionPerformed
        choix = varChoix.getSelectedItem().toString();
        if (choix.equalsIgnoreCase("cipherKey")) {
            btnFile.setText("Clésécréte");
            btnKey.setText("Clépublic");
        } else if (choix.equalsIgnoreCase("cipherMessage")) {
            btnFile.setText("Message");
            btnKey.setText("cipherKey");
        } else if (choix.equalsIgnoreCase("decipherKey")) {
            btnFile.setText("cipherKey");
            btnKey.setText("privKey");

        } else if (choix.equalsIgnoreCase("decipherMessage")) {
            btnFile.setText("ciphermessage");
            btnKey.setText("privKeydeci");

        }
    }//GEN-LAST:event_varChoixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hybride.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hybride.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hybride.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hybride.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hybride().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceuil;
    private javax.swing.JButton btnChiffree;
    private javax.swing.JToggleButton btnCipher;
    private javax.swing.JToggleButton btnDecipher;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnKey;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton quitter;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtKey;
    private javax.swing.JComboBox varChoix;
    // End of variables declaration//GEN-END:variables
}
